# Generated by Django 5.1.5 on 2025-01-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_slug_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, default='No description', max_length=1000, null=True),
        ),
    ]
