# Generated by Django 5.1.5 on 2025-01-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
